### ISSUE TITLE
Module not found: Error: Package path ./highlight.min.js is not exported from package @highlightjs\cdn-assets

### ISSUE THREAD

**Issue by masx200** [highlightjs/highlight.js#3223]
**Describe the issue/behavior that seems buggy**

Module not found: Error: Package path ./highlight.min.js is not exported from package D:\Documents\github\markdown-reader\node_modules\@highlightjs\cdn-assets (see exports field in D:\Documents\github\markdown-reader\node_modules\@highlightjs\cdn-assets\package.json)

**Sample Code or Instructions to Reproduce**

```js
import hljs from "@highlightjs/cdn-assets/highlight.min.js";

export default hljs;
```
**Expected behavior**

**Additional context**

webpack 5.38.1
@highlightjs/cdn-assets 11.0.0

```json
{
   "exports": {
      ".": {
         "require": "./lib/index.js",
         "import": "./es/index.js"
      },
      "./package.json": "./package.json",
      "./lib/common": {
         "require": "./lib/common.js",
         "import": "./es/common.js"
      },
      "./lib/core": {
         "require": "./lib/core.js",
         "import": "./es/core.js"
      },
      "./lib/languages/*": {
         "require": "./lib/languages/*.js",
         "import": "./es/languages/*.js"
      },
      "./scss/*": "./scss/*",
      "./styles/*": "./styles/*",
      "./types/*": "./types/*"
   }
}
```

**Comment by masx200** [comment]
```

> require('@highlightjs/cdn-assets/highlight.min.js')
Uncaught:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './highlight.min.js' is not defined by "exports" in D:\Documents\github\markdown-reader\node_modules\@highlightjs\cdn-assets\package.json
    at new NodeError (node:internal/errors:363:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:321:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:546:3)
    at resolveExports (node:internal/modules/cjs/loader:478:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:518:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:27)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at REPL4:1:1 {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by joshgoebel** [comment]
_Yeah this is a problem, certainly._  Thanks for finding and filing all these issues, but curious - is there a reason  you switched from the regular NPM package to `cdn-assets` now?

Right now I'm of the opinion that cdn-assets shouldn't have export restrictions at all (which would solve this)... but also most people bundling should probably be using the regular package (not con-assets) - so I'm truly curious why you're switching. :-)

**Comment by masx200** [comment]
> _Yeah this is a problem, certainly._ Thanks for finding and filing all these issues, but curious - is there a reason you switched from the regular NPM package to `cdn-assets` now?
> 
> Right now I'm of the opinion that cdn-assets shouldn't have export restrictions at all (which would solve this)... but also most people bundling should probably be using the regular package (not con-assets) - so I'm truly curious why you're switching. :-)

Because I want to use those built-in language modules directly.

**Comment by masx200** [comment]
```js
import hljs from "../node_modules/@highlightjs/cdn-assets/highlight.min.js";
```
I found that as long as it is imported in this way, it works normally.

**Comment by joshgoebel** [comment]
> Because I want to use those built-in language modules directly.

I don't understand.  You can use them directly with the regular NPM package - you don't need to use cdn-assets.

**Comment by joshgoebel** [comment]
Resolved with release of 11.0.1.

Exports are no longer restricted for `cdn-assets`, as this was never the intention.

**Comment by bitencode** [comment]
Not sure this is really fixed yet - it also happens on regular npm package.  I assume it's a problem here because 10.x works but 11.x does not - I don't have this issue with any other npm package.  I migrated to 11.0.0 when it came out and had to roll back to latest 10.x because of this problem.  I upgraded to 11.1.0 this morning and still have this issue.

dependencies:
```javascript
"dependencies": {
  ...
  "highlight.js": "11.1.0",
  "markdown-it": "12.1.0",
  "markdown-it-attrs": "4.0.0",
  ...
}
```

imports:
```javascript
import MarkdownIt from 'markdown-it';
import MarkdownItAttrs from 'markdown-it-attrs';
import hljs from 'highlight.js/lib/core';
import 'highlight.js/styles/github.css';

hljs.registerLanguage('json', require('highlight.js/lib/languages/json'));
hljs.registerLanguage('markdown', require('highlight.js/lib/languages/markdown'));
hljs.registerLanguage('python', require('highlight.js/lib/languages/python'));
hljs.registerLanguage('xml', require('highlight.js/lib/languages/xml'));
hljs.registerLanguage('yaml', require('highlight.js/lib/languages/yaml'));
```

attempt to lint (build same problem, but not from eslint obviously):
```
Oops! Something went wrong! :(

ESLint: 7.29.0

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './styles/github.css' is not defined by "exports" in /Users/johnm/src/sdvi/swarm/node_modules/highlight.js/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:491:3)
    at resolveExports (internal/modules/cjs/loader.js:444:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:484:31)
    at findModulePath (/Users/johnm/src/sdvi/swarm/node_modules/eslint-import-resolver-alias/index.js:99:27)
    at Object.exports.resolve (/Users/johnm/src/sdvi/swarm/node_modules/eslint-import-resolver-alias/index.js:75:10)
    at v2 (/Users/johnm/src/sdvi/swarm/node_modules/eslint-module-utils/resolve.js:117:23)
    at withResolver (/Users/johnm/src/sdvi/swarm/node_modules/eslint-module-utils/resolve.js:122:14)
    at fullResolve (/Users/johnm/src/sdvi/swarm/node_modules/eslint-module-utils/resolve.js:139:22)
    at Function.relative (/Users/johnm/src/sdvi/swarm/node_modules/eslint-module-utils/resolve.js:84:10)
error Command failed with exit code 2.
```

However, this works, but is not right:
```javascript
import MarkdownIt from 'markdown-it';
import MarkdownItAttrs from 'markdown-it-attrs';
import hljs from 'highlight.js/lib/core';
import '../../node_modules/highlight.js/styles/github.css';

/* eslint-disable import/extensions */
hljs.registerLanguage('json', require('../../node_modules/highlight.js/lib/languages/json'));
hljs.registerLanguage('markdown', require('../../node_modules/highlight.js/lib/languages/markdown'));
hljs.registerLanguage('python', require('../../node_modules/highlight.js/lib/languages/python'));
hljs.registerLanguage('xml', require('../../node_modules/highlight.js/lib/languages/xml'));
hljs.registerLanguage('yaml', require('../../node_modules/highlight.js/lib/languages/yaml'));
```

**Comment by dhruvkb** [comment]
This seems to be broken for me as well. I'm getting the following error message:
```
Module not found: Error: Package path ./lib/languages is not exported from package <path_to_proj>/node_modules/highlight.js (see exports field in <path_to_proj>/node_modules/highlight.js/package.json)
```

This message appears when using the dynamic import syntax
```js
await import(
  /*
   webpackInclude: /(java|javascript|latex|markdown|python|ruby|typescript|xml|yaml)/,
   webpackChunkName: "lang-[request]"
   */
   `highlight.js/lib/languages/${lang}.js`
)
```

Downgrading to the latest v10 release fixes this problem for me so something about the `exports` key in the `package.json` for v11 has to be the cause.

Framework: Vue 3 (Vue CLI 5)
Language: TypeScript
Bundler: Webpack 5

**Comment by joshgoebel** [comment]
There is never any reason to directly import `lib/languages` (there is nothing there, no index, etc) only files _within_ that folder, which the wildcard subpath pattern should already cover.  Having to specify the top-level directory also seems broken and entirely redundant to me.  I can find no indication that subpath patterns should not be sufficient.  Subpath folder mappings (as suggest above) are also deprecated...

https://nodejs.org/api/packages.html#packages_subpath_patterns

Perhaps file an issue against Webpack if that is what is kicking up the error?

**Comment by dhruvkb** [comment]
I'm quite confused by this error myself. The workarounds also seem to work without any reason or explanation.

**Comment by joshgoebel** [comment]
I realize that. That's why I suggested file a bug against your packaging software. Of course you can link to this issue and we'll see where things land.
